
// This file has been generated by the GUI designer. Do not modify.
namespace SimpleLauncher
{
	public partial class MainWindow
	{
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Image image5;
		private global::Gtk.Image image6;
		private global::Gtk.Image image7;
		private global::Gtk.ProgressBar progressbar1;
		private global::Gtk.Label labelStatus;
		private global::Gtk.Label labelVersion;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SimpleLauncher.MainWindow
			this.WidthRequest = 480;
			this.HeightRequest = 180;
			this.Name = "SimpleLauncher.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Atmosphir Launcher");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("SimpleLauncher.troposphir_launcher_icon.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultWidth = 483;
			this.DefaultHeight = 180;
			// Container child SimpleLauncher.MainWindow.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.image5 = new global::Gtk.Image ();
			this.image5.Name = "image5";
			this.image5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SimpleLauncher.bg.png");
			this.fixed2.Add (this.image5);
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.image6 = new global::Gtk.Image ();
			this.image6.Name = "image6";
			this.image6.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SimpleLauncher.gear.png");
			this.fixed2.Add (this.image6);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.image6]));
			w2.X = 186;
			w2.Y = 18;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.image7 = new global::Gtk.Image ();
			this.image7.Name = "image7";
			this.image7.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SimpleLauncher.nogear.png");
			this.fixed2.Add (this.image7);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.image7]));
			w3.X = 186;
			w3.Y = 18;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.progressbar1 = new global::Gtk.ProgressBar ();
			this.progressbar1.WidthRequest = 378;
			this.progressbar1.Name = "progressbar1";
			this.progressbar1.Text = global::Mono.Unix.Catalog.GetString ("0%");
			this.fixed2.Add (this.progressbar1);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.progressbar1]));
			w4.X = 56;
			w4.Y = 136;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.labelStatus = new global::Gtk.Label ();
			this.labelStatus.Name = "labelStatus";
			this.labelStatus.LabelProp = global::Mono.Unix.Catalog.GetString ("Checking for updates...");
			this.fixed2.Add (this.labelStatus);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.labelStatus]));
			w5.X = 60;
			w5.Y = 116;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.labelVersion = new global::Gtk.Label ();
			this.labelVersion.Name = "labelVersion";
			this.labelVersion.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.fixed2.Add (this.labelVersion);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.labelVersion]));
			w6.X = 48;
			w6.Y = 161;
			this.Add (this.fixed2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.labelVersion.Hide ();
			this.Show ();
		}
	}
}
